# compose syntax version.
version: "3.6"

# services declaration.
services:
  app:
    image: node:alpine
    working_dir: /root/app/
    #command: npm run dev > /root/logs/backend.log
    command: npm run dev
    environment:
      DB_ADDR: database
      DB_PORT: 5432
      DB_USER: odaw
      DB_PASS: BatidaDe4Banana
      PORT: 5000
    ports:
      - 5000:5000
    depends_on:
      - database
    volumes:
      - ./logs/:/root/logs
      - ./app/:/root/app
    networks:
      - appnetwork

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: odaw
      POSTGRES_PASSWORD: BatidaDe4Banana
      PGDATA: /var/lib/postgresql/data/pgdata
    #volumes:
    #  - ./db/:/var/lib/postgresql/data/pgdata
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
